sudo: required

language: python

services:
  - docker

before_script:
  -sudo docker-compose build
  -sudo docker-compose up -d
  -sudo docker exec -it cvat sh -c '/usr/bin/python3 ~/manage.py createsuperuser'
  -admin
  -123
  -123
  -123

script:
  -
