sudo: required

language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

services:
  - docker

before_script:
  - sudo docker-compose -f docker-compose.yml -f docker-compose-ci.yml build
  - sudo docker-compose up -d
  - docker exec -it cvat sh -c '/usr/bin/python3 ~/manage.py createsuperuser'
  - admin
  - 123
  - 123
  - 123

script:
