sudo: required

language: python

python:
  - "3.5"

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose-ci.yml build
  - docker-compose up -d
  
script:
  - /home/django/tests/node_modules/.bin/karma

