sudo: required

language: node_js

services:
  - docker
  
env:
  - COVERALLS_REPO_TOKEN=S8AMWXHilyXVVrhjpkWUcOlA07KM8AoPR
install:
  - npm install coveralls
before_script:
  - docker-compose -f docker-compose.yml -f docker-compose-ci.yml build
  - docker-compose up -d
  
script:
  - docker exec -it cvat /bin/bash -c '/home/django/tests/node_modules/.bin/karma start tests/karma.conf.js'
after_success:
  - sudo docker exec -it cvat sh -c 'cat media/coverage/lcov.info | tests/node_modules/coveralls/bin/coveralls.js'
