sudo: required

language: python

python:
  - "3.5"

services:
  - docker

install:
  - pip install python-coveralls
  - pip install coverage
  
before_script:
  - docker-compose -f docker-compose.yml -f docker-compose-ci.yml build
  - docker-compose up -d
  
script:
  - docker exec -it cvat sh -c '/tests/node_modules/.bin ~/karma start'

after_success:
  -coveralls
